# Generated by Django 5.0.4 on 2024-04-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regandloginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='cpassword',
            field=models.CharField(max_length=10),
        ),
    ]
